name:                Hustle
version:             0.1.0.0
github:              "fuzzypixelz/Hustle"
license:             MIT
author:              "Mahmoud Mazouz"
maintainer:          "mazouz.mahmoud@outlook.com"
copyright:           "2021 Mahmoud Mazouz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Haskell implementation of the KDL Document Language 

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fuzzypixelz/Hustle#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- text
- megaparsec
- scientific
- prettyprinter

library:
  source-dirs: src
  exposed-modules:     KDL

executables:
  Hustle-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - Hustle

tests:
  Hustle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    defaults: hspec/hspec@master
    dependencies:
    - Hustle
    - QuickCheck
    - directory
    - filepath
